version: "3.9"

services:
  app:
    image: laravel-evaluasiosv2:latest
    container_name: laravel-evaluasiosv2
    restart: unless-stopped
    networks:
      - app-network
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: mysql
      DB_DATABASE: evaluasi_os
      DB_USERNAME: root
      DB_PASSWORD: ""

networks:
  app-network:
    external: true
